# .goreleaser.yml
# Build customization
builds:
  - main: ./gobgp/
    binary: gobgp
    goos:
      - darwin
      - linux
    goarch:
      - amd64

  - main: ./gobgpd/
    binary: gobgpd
  
archive:
  files:
    - LICENSE
    - README.md
