// Code generated by protoc-gen-go. DO NOT EDIT.
// source: capability.proto

package gobgpapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AddPathMode int32

const (
	AddPathMode_MODE_NONE    AddPathMode = 0
	AddPathMode_MODE_RECEIVE AddPathMode = 1
	AddPathMode_MODE_SEND    AddPathMode = 2
	AddPathMode_MODE_BOTH    AddPathMode = 3
)

var AddPathMode_name = map[int32]string{
	0: "MODE_NONE",
	1: "MODE_RECEIVE",
	2: "MODE_SEND",
	3: "MODE_BOTH",
}
var AddPathMode_value = map[string]int32{
	"MODE_NONE":    0,
	"MODE_RECEIVE": 1,
	"MODE_SEND":    2,
	"MODE_BOTH":    3,
}

func (x AddPathMode) String() string {
	return proto.EnumName(AddPathMode_name, int32(x))
}
func (AddPathMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type MultiProtocolCapability struct {
	Family *Family `protobuf:"bytes,1,opt,name=family" json:"family,omitempty"`
}

func (m *MultiProtocolCapability) Reset()                    { *m = MultiProtocolCapability{} }
func (m *MultiProtocolCapability) String() string            { return proto.CompactTextString(m) }
func (*MultiProtocolCapability) ProtoMessage()               {}
func (*MultiProtocolCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *MultiProtocolCapability) GetFamily() *Family {
	if m != nil {
		return m.Family
	}
	return nil
}

type RouteRefreshCapability struct {
}

func (m *RouteRefreshCapability) Reset()                    { *m = RouteRefreshCapability{} }
func (m *RouteRefreshCapability) String() string            { return proto.CompactTextString(m) }
func (*RouteRefreshCapability) ProtoMessage()               {}
func (*RouteRefreshCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type CarryingLabelInfoCapability struct {
}

func (m *CarryingLabelInfoCapability) Reset()                    { *m = CarryingLabelInfoCapability{} }
func (m *CarryingLabelInfoCapability) String() string            { return proto.CompactTextString(m) }
func (*CarryingLabelInfoCapability) ProtoMessage()               {}
func (*CarryingLabelInfoCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type ExtendedNexthopCapabilityTuple struct {
	NlriFamily *Family `protobuf:"bytes,1,opt,name=nlri_family,json=nlriFamily" json:"nlri_family,omitempty"`
	// Nexthop AFI must be either
	// gobgp.IPv4 or
	// gobgp.IPv6.
	NexthopFamily *Family `protobuf:"bytes,2,opt,name=nexthop_family,json=nexthopFamily" json:"nexthop_family,omitempty"`
}

func (m *ExtendedNexthopCapabilityTuple) Reset()                    { *m = ExtendedNexthopCapabilityTuple{} }
func (m *ExtendedNexthopCapabilityTuple) String() string            { return proto.CompactTextString(m) }
func (*ExtendedNexthopCapabilityTuple) ProtoMessage()               {}
func (*ExtendedNexthopCapabilityTuple) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *ExtendedNexthopCapabilityTuple) GetNlriFamily() *Family {
	if m != nil {
		return m.NlriFamily
	}
	return nil
}

func (m *ExtendedNexthopCapabilityTuple) GetNexthopFamily() *Family {
	if m != nil {
		return m.NexthopFamily
	}
	return nil
}

type ExtendedNexthopCapability struct {
	Tuples []*ExtendedNexthopCapabilityTuple `protobuf:"bytes,1,rep,name=tuples" json:"tuples,omitempty"`
}

func (m *ExtendedNexthopCapability) Reset()                    { *m = ExtendedNexthopCapability{} }
func (m *ExtendedNexthopCapability) String() string            { return proto.CompactTextString(m) }
func (*ExtendedNexthopCapability) ProtoMessage()               {}
func (*ExtendedNexthopCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *ExtendedNexthopCapability) GetTuples() []*ExtendedNexthopCapabilityTuple {
	if m != nil {
		return m.Tuples
	}
	return nil
}

type GracefulRestartCapabilityTuple struct {
	Family *Family `protobuf:"bytes,1,opt,name=family" json:"family,omitempty"`
	Flags  uint32  `protobuf:"varint,2,opt,name=flags" json:"flags,omitempty"`
}

func (m *GracefulRestartCapabilityTuple) Reset()                    { *m = GracefulRestartCapabilityTuple{} }
func (m *GracefulRestartCapabilityTuple) String() string            { return proto.CompactTextString(m) }
func (*GracefulRestartCapabilityTuple) ProtoMessage()               {}
func (*GracefulRestartCapabilityTuple) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *GracefulRestartCapabilityTuple) GetFamily() *Family {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *GracefulRestartCapabilityTuple) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

type GracefulRestartCapability struct {
	Flags  uint32                            `protobuf:"varint,1,opt,name=flags" json:"flags,omitempty"`
	Time   uint32                            `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Tuples []*GracefulRestartCapabilityTuple `protobuf:"bytes,3,rep,name=tuples" json:"tuples,omitempty"`
}

func (m *GracefulRestartCapability) Reset()                    { *m = GracefulRestartCapability{} }
func (m *GracefulRestartCapability) String() string            { return proto.CompactTextString(m) }
func (*GracefulRestartCapability) ProtoMessage()               {}
func (*GracefulRestartCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *GracefulRestartCapability) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *GracefulRestartCapability) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *GracefulRestartCapability) GetTuples() []*GracefulRestartCapabilityTuple {
	if m != nil {
		return m.Tuples
	}
	return nil
}

type FourOctetASNumberCapability struct {
	As uint32 `protobuf:"varint,1,opt,name=as" json:"as,omitempty"`
}

func (m *FourOctetASNumberCapability) Reset()                    { *m = FourOctetASNumberCapability{} }
func (m *FourOctetASNumberCapability) String() string            { return proto.CompactTextString(m) }
func (*FourOctetASNumberCapability) ProtoMessage()               {}
func (*FourOctetASNumberCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *FourOctetASNumberCapability) GetAs() uint32 {
	if m != nil {
		return m.As
	}
	return 0
}

type AddPathCapabilityTuple struct {
	Family *Family     `protobuf:"bytes,1,opt,name=family" json:"family,omitempty"`
	Mode   AddPathMode `protobuf:"varint,2,opt,name=mode,enum=gobgpapi.AddPathMode" json:"mode,omitempty"`
}

func (m *AddPathCapabilityTuple) Reset()                    { *m = AddPathCapabilityTuple{} }
func (m *AddPathCapabilityTuple) String() string            { return proto.CompactTextString(m) }
func (*AddPathCapabilityTuple) ProtoMessage()               {}
func (*AddPathCapabilityTuple) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *AddPathCapabilityTuple) GetFamily() *Family {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *AddPathCapabilityTuple) GetMode() AddPathMode {
	if m != nil {
		return m.Mode
	}
	return AddPathMode_MODE_NONE
}

type AddPathCapability struct {
	Tuples []*AddPathCapabilityTuple `protobuf:"bytes,1,rep,name=tuples" json:"tuples,omitempty"`
}

func (m *AddPathCapability) Reset()                    { *m = AddPathCapability{} }
func (m *AddPathCapability) String() string            { return proto.CompactTextString(m) }
func (*AddPathCapability) ProtoMessage()               {}
func (*AddPathCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *AddPathCapability) GetTuples() []*AddPathCapabilityTuple {
	if m != nil {
		return m.Tuples
	}
	return nil
}

type EnhancedRouteRefreshCapability struct {
}

func (m *EnhancedRouteRefreshCapability) Reset()         { *m = EnhancedRouteRefreshCapability{} }
func (m *EnhancedRouteRefreshCapability) String() string { return proto.CompactTextString(m) }
func (*EnhancedRouteRefreshCapability) ProtoMessage()    {}
func (*EnhancedRouteRefreshCapability) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{10}
}

type LongLivedGracefulRestartCapabilityTuple struct {
	Family *Family `protobuf:"bytes,1,opt,name=family" json:"family,omitempty"`
	Flags  uint32  `protobuf:"varint,2,opt,name=flags" json:"flags,omitempty"`
	Time   uint32  `protobuf:"varint,3,opt,name=time" json:"time,omitempty"`
}

func (m *LongLivedGracefulRestartCapabilityTuple) Reset() {
	*m = LongLivedGracefulRestartCapabilityTuple{}
}
func (m *LongLivedGracefulRestartCapabilityTuple) String() string { return proto.CompactTextString(m) }
func (*LongLivedGracefulRestartCapabilityTuple) ProtoMessage()    {}
func (*LongLivedGracefulRestartCapabilityTuple) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{11}
}

func (m *LongLivedGracefulRestartCapabilityTuple) GetFamily() *Family {
	if m != nil {
		return m.Family
	}
	return nil
}

func (m *LongLivedGracefulRestartCapabilityTuple) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *LongLivedGracefulRestartCapabilityTuple) GetTime() uint32 {
	if m != nil {
		return m.Time
	}
	return 0
}

type LongLivedGracefulRestartCapability struct {
	Tuples []*LongLivedGracefulRestartCapabilityTuple `protobuf:"bytes,1,rep,name=tuples" json:"tuples,omitempty"`
}

func (m *LongLivedGracefulRestartCapability) Reset()         { *m = LongLivedGracefulRestartCapability{} }
func (m *LongLivedGracefulRestartCapability) String() string { return proto.CompactTextString(m) }
func (*LongLivedGracefulRestartCapability) ProtoMessage()    {}
func (*LongLivedGracefulRestartCapability) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{12}
}

func (m *LongLivedGracefulRestartCapability) GetTuples() []*LongLivedGracefulRestartCapabilityTuple {
	if m != nil {
		return m.Tuples
	}
	return nil
}

type RouteRefreshCiscoCapability struct {
}

func (m *RouteRefreshCiscoCapability) Reset()                    { *m = RouteRefreshCiscoCapability{} }
func (m *RouteRefreshCiscoCapability) String() string            { return proto.CompactTextString(m) }
func (*RouteRefreshCiscoCapability) ProtoMessage()               {}
func (*RouteRefreshCiscoCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

type FQDNCapability struct {
	HostNameLen   uint32 `protobuf:"varint,1,opt,name=host_name_len,json=hostNameLen" json:"host_name_len,omitempty"`
	HostName      []byte `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	DomainNameLen uint32 `protobuf:"varint,3,opt,name=domain_name_len,json=domainNameLen" json:"domain_name_len,omitempty"`
	DomainName    []byte `protobuf:"bytes,4,opt,name=domain_name,json=domainName,proto3" json:"domain_name,omitempty"`
}

func (m *FQDNCapability) Reset()                    { *m = FQDNCapability{} }
func (m *FQDNCapability) String() string            { return proto.CompactTextString(m) }
func (*FQDNCapability) ProtoMessage()               {}
func (*FQDNCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *FQDNCapability) GetHostNameLen() uint32 {
	if m != nil {
		return m.HostNameLen
	}
	return 0
}

func (m *FQDNCapability) GetHostName() []byte {
	if m != nil {
		return m.HostName
	}
	return nil
}

func (m *FQDNCapability) GetDomainNameLen() uint32 {
	if m != nil {
		return m.DomainNameLen
	}
	return 0
}

func (m *FQDNCapability) GetDomainName() []byte {
	if m != nil {
		return m.DomainName
	}
	return nil
}

type UnknownCapability struct {
	Code  uint32 `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Value []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *UnknownCapability) Reset()                    { *m = UnknownCapability{} }
func (m *UnknownCapability) String() string            { return proto.CompactTextString(m) }
func (*UnknownCapability) ProtoMessage()               {}
func (*UnknownCapability) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *UnknownCapability) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UnknownCapability) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*MultiProtocolCapability)(nil), "gobgpapi.MultiProtocolCapability")
	proto.RegisterType((*RouteRefreshCapability)(nil), "gobgpapi.RouteRefreshCapability")
	proto.RegisterType((*CarryingLabelInfoCapability)(nil), "gobgpapi.CarryingLabelInfoCapability")
	proto.RegisterType((*ExtendedNexthopCapabilityTuple)(nil), "gobgpapi.ExtendedNexthopCapabilityTuple")
	proto.RegisterType((*ExtendedNexthopCapability)(nil), "gobgpapi.ExtendedNexthopCapability")
	proto.RegisterType((*GracefulRestartCapabilityTuple)(nil), "gobgpapi.GracefulRestartCapabilityTuple")
	proto.RegisterType((*GracefulRestartCapability)(nil), "gobgpapi.GracefulRestartCapability")
	proto.RegisterType((*FourOctetASNumberCapability)(nil), "gobgpapi.FourOctetASNumberCapability")
	proto.RegisterType((*AddPathCapabilityTuple)(nil), "gobgpapi.AddPathCapabilityTuple")
	proto.RegisterType((*AddPathCapability)(nil), "gobgpapi.AddPathCapability")
	proto.RegisterType((*EnhancedRouteRefreshCapability)(nil), "gobgpapi.EnhancedRouteRefreshCapability")
	proto.RegisterType((*LongLivedGracefulRestartCapabilityTuple)(nil), "gobgpapi.LongLivedGracefulRestartCapabilityTuple")
	proto.RegisterType((*LongLivedGracefulRestartCapability)(nil), "gobgpapi.LongLivedGracefulRestartCapability")
	proto.RegisterType((*RouteRefreshCiscoCapability)(nil), "gobgpapi.RouteRefreshCiscoCapability")
	proto.RegisterType((*FQDNCapability)(nil), "gobgpapi.FQDNCapability")
	proto.RegisterType((*UnknownCapability)(nil), "gobgpapi.UnknownCapability")
	proto.RegisterEnum("gobgpapi.AddPathMode", AddPathMode_name, AddPathMode_value)
}

func init() { proto.RegisterFile("capability.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x49, 0x88, 0xda, 0x71, 0x13, 0xdc, 0x15, 0x94, 0x94, 0xa8, 0x21, 0xda, 0x03, 0x04,
	0x24, 0x22, 0x35, 0x1c, 0xe0, 0x82, 0x44, 0x49, 0x1c, 0x88, 0x94, 0x38, 0xc5, 0x2d, 0xdc, 0x50,
	0xd8, 0xd8, 0x9b, 0xc4, 0xc2, 0xde, 0xb5, 0xec, 0x75, 0x69, 0x0e, 0x9c, 0xb9, 0xf0, 0x0b, 0xf8,
	0xb5, 0xc8, 0xdf, 0x26, 0x55, 0xda, 0x0a, 0x89, 0xdb, 0xce, 0xce, 0x9b, 0x37, 0xef, 0xcd, 0x8e,
	0x0d, 0x8a, 0x41, 0x5c, 0x32, 0xb7, 0x6c, 0x4b, 0xac, 0xbb, 0xae, 0xc7, 0x05, 0x47, 0x3b, 0x4b,
	0x3e, 0x5f, 0xba, 0xc4, 0xb5, 0x1e, 0xc9, 0xd1, 0x29, 0xbe, 0xc6, 0x7d, 0x78, 0x38, 0x09, 0x6c,
	0x61, 0x9d, 0x86, 0x91, 0xc1, 0xed, 0x7e, 0x56, 0x87, 0x3a, 0x50, 0x5d, 0x10, 0xc7, 0xb2, 0xd7,
	0x0d, 0xa9, 0x2d, 0x75, 0xe4, 0x9e, 0xd2, 0x4d, 0x29, 0xba, 0xc3, 0xe8, 0x5e, 0x4f, 0xf2, 0xb8,
	0x01, 0x07, 0x3a, 0x0f, 0x04, 0xd5, 0xe9, 0xc2, 0xa3, 0xfe, 0x2a, 0xe7, 0xc0, 0x47, 0xd0, 0xec,
	0x13, 0xcf, 0x5b, 0x5b, 0x6c, 0x39, 0x26, 0x73, 0x6a, 0x8f, 0xd8, 0x82, 0x17, 0xd2, 0xbf, 0x24,
	0x68, 0xa9, 0x97, 0x82, 0x32, 0x93, 0x9a, 0x1a, 0xbd, 0x14, 0x2b, 0xee, 0xe6, 0xd9, 0xf3, 0xc0,
	0xb5, 0x29, 0x3a, 0x06, 0x99, 0xd9, 0x9e, 0x35, 0xbb, 0x41, 0x0a, 0x84, 0xa0, 0xf8, 0x8c, 0x5e,
	0x41, 0x9d, 0xc5, 0x64, 0x69, 0x55, 0x69, 0x4b, 0x55, 0x2d, 0xc1, 0xc5, 0x21, 0xfe, 0x02, 0x87,
	0x5b, 0xd5, 0xa0, 0xb7, 0x50, 0x15, 0xa1, 0x22, 0xbf, 0x21, 0xb5, 0xcb, 0x1d, 0xb9, 0xd7, 0xc9,
	0xd9, 0xae, 0xb7, 0xa0, 0x27, 0x75, 0xf8, 0x2b, 0xb4, 0xde, 0x7b, 0xc4, 0xa0, 0x8b, 0xc0, 0xd6,
	0xa9, 0x2f, 0x88, 0x27, 0x36, 0xcd, 0xde, 0x7a, 0xe4, 0xe8, 0x3e, 0xdc, 0x5d, 0xd8, 0x64, 0xe9,
	0x47, 0xd6, 0x6a, 0x7a, 0x1c, 0xe0, 0x9f, 0x12, 0x1c, 0x6e, 0x6d, 0x91, 0xd7, 0x48, 0x85, 0x1a,
	0x84, 0xa0, 0x22, 0x2c, 0x87, 0x26, 0x44, 0xd1, 0xb9, 0xe0, 0xb5, 0xbc, 0xe9, 0xf5, 0x7a, 0x07,
	0x99, 0xd7, 0x17, 0xd0, 0x1c, 0xf2, 0xc0, 0x9b, 0x1a, 0x82, 0x8a, 0x93, 0x33, 0x2d, 0x70, 0xe6,
	0xd4, 0x2b, 0x48, 0xa9, 0x43, 0x89, 0xa4, 0x3a, 0x4a, 0xc4, 0xc7, 0x0e, 0x1c, 0x9c, 0x98, 0xe6,
	0x29, 0x11, 0xab, 0x7f, 0x1f, 0xc9, 0x33, 0xa8, 0x38, 0xdc, 0x8c, 0x8d, 0xd4, 0x7b, 0x0f, 0x72,
	0x5c, 0xc2, 0x3c, 0xe1, 0x26, 0xd5, 0x23, 0x08, 0x9e, 0xc0, 0xfe, 0x95, 0x76, 0xe8, 0xf5, 0xc6,
	0x03, 0xb7, 0xaf, 0x30, 0x6c, 0x33, 0xdb, 0x86, 0x96, 0xca, 0x56, 0x84, 0x19, 0xd4, 0xdc, 0xf2,
	0x1d, 0xfc, 0x80, 0xa7, 0x63, 0xce, 0x96, 0x63, 0xeb, 0x82, 0x9a, 0xff, 0x77, 0x07, 0xb2, 0xf7,
	0x2c, 0xe7, 0xef, 0x89, 0x39, 0xe0, 0x9b, 0xdb, 0xa3, 0xd1, 0xc6, 0x00, 0x8e, 0xf3, 0xce, 0xb7,
	0x14, 0x9f, 0x4d, 0xe4, 0x08, 0x9a, 0x7f, 0x4d, 0xc2, 0xf2, 0x8d, 0xe2, 0x77, 0xff, 0x5b, 0x82,
	0xfa, 0xf0, 0xe3, 0x40, 0x2b, 0x34, 0xc7, 0x50, 0x5b, 0x71, 0x5f, 0xcc, 0x18, 0x71, 0xe8, 0xcc,
	0xa6, 0x2c, 0x59, 0x0e, 0x39, 0xbc, 0xd4, 0x88, 0x43, 0xc7, 0x94, 0xa1, 0x26, 0xec, 0x66, 0x98,
	0xc8, 0xf4, 0x9e, 0xbe, 0x93, 0xe6, 0xd1, 0x13, 0xb8, 0x67, 0x72, 0x87, 0x58, 0x2c, 0xa7, 0x88,
	0x47, 0x50, 0x8b, 0xaf, 0x53, 0x92, 0xc7, 0x20, 0x17, 0x70, 0x8d, 0x4a, 0x44, 0x03, 0x39, 0x06,
	0xbf, 0x81, 0xfd, 0x4f, 0xec, 0x1b, 0xe3, 0xdf, 0x59, 0x41, 0x1e, 0x82, 0x8a, 0x11, 0x2e, 0x57,
	0xac, 0x2a, 0x3a, 0x87, 0xf3, 0xbf, 0x20, 0x76, 0x90, 0x4a, 0x89, 0x83, 0xe7, 0x63, 0x90, 0x0b,
	0x0b, 0x87, 0x6a, 0xb0, 0x3b, 0x99, 0x0e, 0xd4, 0x99, 0x36, 0xd5, 0x54, 0xe5, 0x0e, 0x52, 0x60,
	0x2f, 0x0a, 0x75, 0xb5, 0xaf, 0x8e, 0x3e, 0xab, 0x8a, 0x94, 0x01, 0xce, 0x54, 0x6d, 0xa0, 0x94,
	0xb2, 0xf0, 0xdd, 0xf4, 0xfc, 0x83, 0x52, 0x9e, 0x57, 0xa3, 0xdf, 0xf4, 0xcb, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xba, 0x43, 0x59, 0x28, 0xd1, 0x05, 0x00, 0x00,
}
